### ISSUE TITLE
Getting crash on SmartLoginOptions from facebook SDK

### ISSUE THREAD

**Issue by athulantonynp** [facebook/facebook-android-sdk#973] opened 2021-06-23 11:52 UTC
Our Facebook SDK crashes on some user's devices. We couldn't recreate this from our end. Here is the stack trace found in crashlytics

```java

Fatal Exception: java.lang.ExceptionInInitializerError
       at com.facebook.internal.SmartLoginOption.parseOptions(SmartLoginOption.java:31)
       at com.facebook.internal.FetchedAppSettingsManager.parseAppSettingsFromJSON(FetchedAppSettingsManager.java:329)
       at com.facebook.internal.FetchedAppSettingsManager.access$000(FetchedAppSettingsManager.java:63)
       at com.facebook.internal.FetchedAppSettingsManager$1.run(FetchedAppSettingsManager.java:174)
       at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1167)
       at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:641)
       at java.lang.Thread.run(Thread.java:923)
Caused by java.lang.RuntimeException: java.lang.NoSuchMethodException: com.facebook.internal.u.values []
       at java.lang.Enum.enumValues(Enum.java:270)
       at java.lang.Enum.access$000(Enum.java:61)
       at java.lang.Enum$1.create(Enum.java:277)
       at java.lang.Enum$1.create(Enum.java:275)
       at libcore.util.BasicLruCache.get(BasicLruCache.java:63)
       at java.lang.Enum.getSharedConstants(Enum.java:289)
       at java.lang.Class.getEnumConstantsShared(Class.java:2428)
       at java.util.EnumSet.getUniverse(EnumSet.java:407)
       at java.util.EnumSet.noneOf(EnumSet.java:109)
       at java.util.EnumSet.allOf(EnumSet.java:130)
       at com.facebook.internal.SmartLoginOption.<clinit>(SmartLoginOption.java:29)
       at com.facebook.internal.SmartLoginOption.parseOptions(SmartLoginOption.java:31)
       at com.facebook.internal.FetchedAppSettingsManager.parseAppSettingsFromJSON(FetchedAppSettingsManager.java:329)
       at com.facebook.internal.FetchedAppSettingsManager.access$000(FetchedAppSettingsManager.java:63)
       at com.facebook.internal.FetchedAppSettingsManager$1.run(FetchedAppSettingsManager.java:174)
       at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1167)
       at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:641)
       at java.lang.Thread.run(Thread.java:923)

```

**Comment by linmx0130** [comment] 2021-06-26 02:30
Hi @athulantonynp, thanks for raising this issue. Could you have a check on the SDK version of the crashed app? It seems that it's from a really old SDK version, which is not fully supported.

**Comment by Uwdieyn-Network-Team** [comment] 2021-07-28 20:44
Fatal Exception: java.lang.ExceptionInInitializerError
       at com.facebook.internal.SmartLoginOption.parseOptions(SmartLoginOption.java:31)
       at com.facebook.internal.FetchedAppSettingsManager.parseAppSettingsFromJSON(FetchedAppSettingsManager.java:329)
       at com.facebook.internal.FetchedAppSettingsManager.access$000(FetchedAppSettingsManager.java:63)
       at com.facebook.internal.FetchedAppSettingsManager$1.run(FetchedAppSettingsManager.java:174)
       at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1167)
       at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:641)
       at java.lang.Thread.run(Thread.java:923)
Caused by java.lang.RuntimeException: java.lang.NoSuchMethodException: com.facebook.internal.u.values []
       at java.lang.Enum.enumValues(Enum.java:270)
       at java.lang.Enum.access$000(Enum.java:61)
       at java.lang.Enum$1.create(Enum.java:277)
       at java.lang.Enum$1.create(Enum.java:275)
       at libcore.util.BasicLruCache.get(BasicLruCache.java:63)
       at java.lang.Enum.getSharedConstants(Enum.java:289)
       at java.lang.Class.getEnumConstantsShared(Class.java:2428)
       at java.util.EnumSet.getUniverse(EnumSet.java:407)
       at java.util.EnumSet.noneOf(EnumSet.java:109)
       at java.util.EnumSet.allOf(EnumSet.java:130)
       at com.facebook.internal.SmartLoginOption.<clinit>(SmartLoginOption.java:29)
       at com.facebook.internal.SmartLoginOption.parseOptions(SmartLoginOption.java:31)
       at com.facebook.internal.FetchedAppSettingsManager.parseAppSettingsFromJSON(FetchedAppSettingsManager.java:329)
       at com.facebook.internal.FetchedAppSettingsManager.access$000(FetchedAppSettingsManager.java:63)
       at com.facebook.internal.FetchedAppSettingsManager$1.run(FetchedAppSettingsManager.java:174)
       at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1167)
       at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:641)
       at java.lang.Thread.run(Thread.java:923)

**Comment by jingping2015** [comment] 2021-09-27 20:58
Close it since no SDK version be provided.

**Closed by jingping2015** 2021-09-27 20:58 UTC
