### ISSUE TITLE
Google Api Error: apkNotificationMessageKeyBundleTargetsInvalidLanguage: The bundle targets unrecognized languages: fb.

### ISSUE THREAD

**Issue by aliguvenc** [facebook/facebook-android-sdk#614] opened 2019-10-30 11:51 UTC
after compiling with android sdk 5.9.0, in genereted res directory there is a folder named values-fb and it seems like app bundle generates a split apk for fb language which is an undefined language for google. It throws an error like Google Api Error: apkNotificationMessageKeyBundleTargetsInvalidLanguage: The bundle targets unrecognized languages: fb.After downgrading to 5.8.0 problem resolved

**Comment by marshallcool** [comment] 2019-10-30 13:46
@aliguvenc are you .aab build ?

**Comment by aliguvenc** [comment] 2019-10-30 13:50
@marshallcool yes

**Comment by marshallcool** [comment] 2019-10-30 13:55
I think fb were not ready for people to build aab, not apk

**Comment by pixeption** [comment] 2019-10-31 03:54
I got the same issue when uploading to PlayStore

> Your App Bundle targets the following unrecognized languages: fb. The list of supported language codes can be found in the IANA registry. Invalid languages caused by third-party libraries can be excluded using the resConfigs Gradle property.

I forced the SDK to 5.8.0 rather ran using `resConfigs`

**Comment by zukinaru** [comment] 2019-11-01 10:33
This impact me who use `flutter`, see also https://stackoverflow.com/questions/58655465/fastlane-cant-publish-to-google-playstore

i'm using this plugin: **flutter_facebook_login: ^2.0.1**

**Comment by marshallcool** [comment] 2019-11-01 10:50
> This impact me who use `flutter`

does `flutter_facebook_login` work without?

**Comment by mayurdhurpate** [comment] 2019-11-01 11:12
cc @roughike Do we need to have a hotfix for [flutter_facebook_login](https://github.com/roughike/flutter_facebook_login) to force the Facebook SDK to 5.8.0 or use `resConfigs`?

**Comment by zukinaru** [comment] 2019-11-01 13:23
> > This impact me who use `flutter`
> 
> does `flutter_facebook_login` work without?

i remove this plugin but still get "Publishing failed :| Failed to publish: The bundle targets unrecognized languages: fb."

any idea ?

because my code nothing change but suddenly face this error.

**Comment by zukinaru** [comment] 2019-11-01 14:16
but, if I choose to build APK instead of App Bundle. it will succeed to be uploaded to the play store.

Although the size increase from 23 MB to 31 MB...

**Comment by marshallcool** [comment] 2019-11-01 16:26
> but, if I choose to build APK instead of App Bundle. it will succeed to be uploaded to the play store.
> 
> Although the size increase from 23 MB to 31 MB...

`resConfigs "en", "US"` in build.gradle

**Comment by zukinaru** [comment] 2019-11-01 21:54
> > but, if I choose to build APK instead of App Bundle. it will succeed to be uploaded to the play store.
> > Although the size increase from 23 MB to 31 MB...
> 
> `resConfigs "en", "US"` in build.gradle

where i need to write this ?

in `build.gradle` or `app/build.gradle`

and under any node ?

**Comment by iutinvg** [comment] 2019-11-02 07:12
> where do i need to write resConfigs "en", "US"?
```
android { 
   defaultConfig {
        ...
        resConfigs "en", "US" 
        ...
   }
}
```

**Comment by MrLoh** [comment] 2019-11-02 23:28
Thanks for the workaround. Would be nice if Facebook could provide a real fix though.

**Comment by piotrros** [comment] 2019-11-04 09:33
Without this fix you cannot send an app to Google Play (if using AAB).

**Comment by riocallos** [comment] 2019-11-04 13:25
will the reConfig fix work if my app needs to support 2 locales?

**Comment by YoavU** [comment] 2019-11-05 08:20
This is crazy that Facebook doesn't provide any solution or hotfix version.

**Comment by iutinvg** [comment] 2019-11-05 10:50
> will the reConfig fix work if my app needs to support 2 locales?

Just list all necessary locales:
```
resConfigs "en", "US", "ru"
```

**Comment by jonashartmann** [comment] 2019-11-11 07:32
It seems that the issue is caused by a new folder "res/values-fb" added in the facebook-common module version 5.9.0:
![image](https://user-images.githubusercontent.com/2093985/68569112-9b2b5780-045d-11ea-9661-bd48e3af42ca.png)

**Comment by vorasudh** [comment] 2019-11-12 14:12
Any plans on renaming or removing that folder?

**Comment by milkaman** [comment] 2019-11-18 08:50
Is it still faced in 5.11.0 ?

**Comment by bonbonez** [comment] 2019-11-18 12:06
The issue still exists in `5.11.0`, just tried to upload my AAB to Google Play.

**Comment by jose920405** [comment] 2019-11-18 22:22
I have an error adding `resConfigs` inside `defaultConfig` in `build.gradle`

```
Could not get unknown property 'resConfigs' for SigningConfig_Decorated{name=debug, storeFile=/Users/mac/.android/debug.keystore, storePassword=android, keyAlias=AndroidDebugKey, keyPassword=android, storeType=jks, v1SigningEnabled=true, v2SigningEnabled=true} of type com.android.build.gradle.internal.dsl.SigningConfig. |  
-- | --



```

**Comment by andreguedes** [comment] 2019-11-18 22:32
I have the same problem to upload an .aab! =(

**Comment by hueyenclave** [comment] 2019-11-19 02:28
Hi guys. I'm using v5.6 and our previous release was working fine (~ 3 weeks ago). But I got same issue today, can't release aab to Google Play Console. Updated sdk version to v5.8 but doesn't work. Please check it out and get rid of the issue.

**Comment by martinbonnin** [comment] 2019-11-19 15:53
Looks like this was introduced with https://github.com/facebook/facebook-android-sdk/commit/84f6d253a8da818e30acace712832f2d6ac30986

**Comment by jose920405** [comment] 2019-11-19 15:56
i fix it adding `resConfigs "<myLanguage>", "<MyRegion>"` inside `defaultConfig` in `build.gradle` file.


```
defaultConfig {
        ...
        resConfigs "en", "US"
        ...
    }
```

**Comment by hueyenclave** [comment] 2019-11-20 07:30
> Hi guys. I'm using v5.6 and our previous release was working fine (~ 3 weeks ago). But I got same issue today, can't release aab to Google Play Console. Updated sdk version to v5.8 but doesn't work. Please check it out and get rid of the issue.

Finally, I resolved the issue, we figured out that as we are using dependencies as facebook guidline like this: "[5,6)" so need to be changed to specific version "5.8.0"

In my case:

**Comment by KylinChang** [comment] 2019-11-20 23:02
Hi all, we have removed the issued language and will release a fixed version this week.

**Comment by KylinChang** [comment] 2019-11-22 08:37
The fixed version v5.11.2 was released, close the issue now.

**Closed by KylinChang** 2019-11-22 08:37 UTC

**Comment by fkirc** [comment] 2019-11-25 17:57
I was also facing the same issue.
Is it best practice to explicitly specify the supported languages in `build.gradle`?

**Comment by KylinChang** [comment] 2019-11-25 18:03
Hi @fkirc , are you using v5.11.2?

**Comment by fkirc** [comment] 2019-11-25 18:22
Yes, it is now working after the update to 5.12.2.

**Comment by jam-cmesquita** [comment] 2020-03-11 07:36
Hi there!
I updated yesterday **from 6.0.0** (previous used version, which was working great) **to 6.2.0**, and I get that same thing again:
```
Google Api Error: apkNotificationMessageKeyBundleTargetsInvalidLanguage: 
The bundle targets unrecognized languages: fb.
```

Can you fix this again please?

**Comment by khorark** [comment] 2020-03-11 07:47
> Hi there!
> I updated yesterday **from 6.0.0** (previous used version, which was working great) **to 6.2.0**, and I get that same thing again:
> 
> ```
> Google Api Error: apkNotificationMessageKeyBundleTargetsInvalidLanguage: 
> The bundle targets unrecognized languages: fb.
> ```
> 
> Can you fix this again please?

See https://github.com/facebook/facebook-android-sdk/issues/614#issuecomment-549018018

**Comment by jam-cmesquita** [comment] 2020-03-11 07:59
> > Hi there!
> > I updated yesterday **from 6.0.0** (previous used version, which was working great) **to 6.2.0**, and I get that same thing again:
> > ```
> > Google Api Error: apkNotificationMessageKeyBundleTargetsInvalidLanguage: 
> > The bundle targets unrecognized languages: fb.
> > ```
> > 
> > 
> > Can you fix this again please?
> 
> See [#614 (comment)](https://github.com/facebook/facebook-android-sdk/issues/614#issuecomment-549018018)

I saw that, but they fixed it in the SDK code back then. Check this:
> https://github.com/facebook/facebook-android-sdk/issues/614#issuecomment-556521131

**Comment by falcon4ever** [comment] 2020-03-13 17:41
Same issue above with v6.2.0, downgrading to v6.1.0 works to ship the AAB.

**Comment by Pitel** [comment] 2020-03-25 10:08
Should be reopened, 6.2.0 does it again!

**Comment by joknu1** [comment] 2020-03-26 10:45
Seem to be fixed in 6.3.0

**Comment by emmanuel-marty** [comment] 2020-04-06 15:28
This is still occuring with 6.3.0

**Comment by gommzystudio** [comment] 2021-03-23 10:03
> This is still occuring with 6.3.0

Still all new builds

**Comment by elmoubtahige** [comment] 2022-08-04 04:03
search for folder project and remove values XX

**Comment by JClackett** [comment] 2023-12-19 15:33
Happening again
